#!/bin/sh

# Copyright (C) 2010 Andrea Martire
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

case "$1" in
  start)
	start-stop-daemon --start --exec /usr/bin/aLid &
	exit 0
	;;
  stop)
  	/usr/bin/aLidStop 
	;;
  restart|force-reload)	
	start-stop-daemon --start --exec /usr/bin/aLidStop
	sleep 1
	start-stop-daemon --start --exec /usr/bin/aLid &
	exit 0
	;;
  *)
	echo "Usage: /etc/init.d/aLid {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac



